server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: http://github.com/handle2583/_78.git
          search-paths: config
          username: 1716617301@qq.com
          passphrase: Element4ry
      label: master
eureka:
  client:
    service-url:
      defaultZone: http:localhost:8761/eureka/